#pragma once
#define _CRT_SECURE_NO_WARNINGS
#include <filesystem>
#include <memory>
#include <string>
#include <iostream>
#include <sstream>
#include <functional>
#include <algorithm>
#include <vector>
#include <boost/optional.hpp>
#include <boost/range/algorithm/find_if.hpp>
#include <map>